development:
  clients:
    default:
      database: forestall
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: forestall_test
      hosts:
        - localhost:27017
